### PR TITLE
edit README.md

### PR DESCRIPTION
**Pull request by oliver-sanders**

### CODE REVIEW

**Comment by oliver-sanders** [comment]
This code shows that the variable definitely isn't getting passed through.

https://github.com/peaceiris/actions-gh-pages/blob/dc1169c5baf9ed1205d6f0f9c9ce0e6d26afb164/src/get-inputs.ts#L6-L12

**Comment by oliver-sanders** [comment]
For abd7a62 I created a new secret called `FOO` with value `foo` which if it were passed through would result in SSH failure. This is to test that there isn't any issue with multiline stuff or variable format.

**Comment by kinow** [comment]
Really weird. It looks like it couldn't find the deploy key or any other token, and failed in the last else of `setTokens` https://github.com/peaceiris/actions-gh-pages/blob/25ae83ba65b483195e2a1b7b9a5198c271d0d84c/src/set-tokens.ts#L135

But for me it looks like you used the correct option, `deploy_key`, and that it was supposed to work 😕

**Comment by oliver-sanders** [comment]
Next experiment (f13ea28):

Set the `deploy_key` as plaintext, this should result in an SSH issue, if so then it means that the issue is the templating of the GitHub secret I think.

**Comment by oliver-sanders** [comment]
So then I guess this is the answer?

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

**Comment by kinow** [comment]
> So then I guess this is the answer?
> 
> > Secrets are not passed to workflows that are triggered by a pull request from a fork.

It used to be the same with Codecov until they fixed it a few days ago, and cylc ui coverage works for master and pr's.

**Pull request closed without merging**
